#!/usr/bin/env python3
"""Rebuild INDEX.md from the markdown notes (the browsable view is the `brain` app).

Usage: python3 build.py   (notes folder = parent of this folder, or $BRAIN_NOTES)
Stdlib only. Safe to run any time; the output is fully regenerated.
"""
import datetime
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
NOTES = os.path.abspath(os.path.expanduser(os.environ.get("BRAIN_NOTES") or os.path.dirname(HERE)))
PROJECTS_DIR = os.path.expanduser(os.environ.get("BRAIN_PROJECTS_DIR", "~/Projects"))
SKIP_DIRS = {".brain", ".claude", ".git", ".obsidian"}
OPEN_TASK = re.compile(r"^\s*[-*] \[ \] (.+)$", re.M)


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    meta = {}
    for line in text[4:end].splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, val = line.split(":", 1)
        # Only "  # comment" (2+ spaces) is a comment, so titles like "PR #28" survive.
        val = re.sub(r"\s{2,}#.*$", "", val).strip().strip('"').strip("'")
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip().strip('"').strip("'") for v in val[1:-1].split(",") if v.strip()]
        meta[key.strip()] = val
    return meta, text[end + 4:].lstrip("\n")


def first_heading(body, fallback):
    m = re.search(r"^# (.+)$", body, re.M)
    return m.group(1).strip() if m else fallback


def tldr(body):
    m = re.search(r"\*\*TL;DR:\*\*\s*(.+)", body)
    return m.group(1).strip() if m else ""


def load_notes():
    docs = []
    for dirpath, dirnames, filenames in os.walk(NOTES):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for fn in sorted(filenames):
            if not fn.endswith(".md") or fn == "INDEX.md":
                continue
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, NOTES)
            with open(full, encoding="utf-8", errors="replace") as f:
                meta, body = parse_frontmatter(f.read())
            top = rel.split(os.sep)[0] if os.sep in rel else ""
            kind = {"sessions": "session", "projects": "project"}.get(top, "note")
            mtime = datetime.date.fromtimestamp(os.path.getmtime(full)).isoformat()
            docs.append({
                "path": rel,
                "kind": kind,
                "meta": meta,
                "title": meta.get("title") or meta.get("name") or first_heading(body, fn[:-3]),
                "date": str(meta.get("date") or meta.get("updated") or mtime),
                "tldr": tldr(body) or meta.get("summary", ""),
                "open": OPEN_TASK.findall(body),
                "body": body,
            })
    return docs


def as_list(v):
    if isinstance(v, list):
        return v
    return [v] if v else []


def other_folders(known_paths):
    """~/Projects folders with no project note yet — listed, never summarized."""
    if not os.path.isdir(PROJECTS_DIR):
        return []
    known = {os.path.basename(os.path.expanduser(p).rstrip("/")) for p in known_paths}
    out = []
    for name in sorted(os.listdir(PROJECTS_DIR), key=str.lower):
        full = os.path.join(PROJECTS_DIR, name)
        if name.startswith(".") or not os.path.isdir(full) or name in known:
            continue
        out.append({"name": name, "path": "~/Projects/" + name,
                    "modified": datetime.date.fromtimestamp(os.path.getmtime(full)).isoformat()})
    return out


def build_index(docs, folders):
    projects = sorted((d for d in docs if d["kind"] == "project"),
                      key=lambda d: d["meta"].get("updated", ""), reverse=True)
    sessions = sorted((d for d in docs if d["kind"] == "session"),
                      key=lambda d: d["path"], reverse=True)
    others = [d for d in docs if d["kind"] == "note"]
    by_project = {}
    for s in sessions:
        for p in as_list(s["meta"].get("projects")) or ["misc"]:
            by_project.setdefault(p, []).append(s)

    L = ["# Notes index", "",
         "_Generated by `.brain/build.py` on %s. Do not edit by hand; edit the notes and rebuild._"
         % datetime.date.today().isoformat(), "",
         "Read this first. Open a project page before touching that project; open a session note only",
         "when you need the detail of what happened that day.", "",
         "## Projects", "",
         "| Project | Status | Updated | Summary |", "|---|---|---|---|"]
    for p in projects:
        m = p["meta"]
        L.append("| [%s](%s) | %s | %s | %s |" % (p["title"], p["path"], m.get("status", ""),
                                              m.get("updated", ""),
                                              (m.get("summary") or p["tldr"]).replace("|", "/")))
    L += ["", "## Recent sessions", ""]
    for s in sessions[:25]:
        L.append("- %s · [%s](%s) · `%s` · %s" % (
            s["meta"].get("date", ""), s["title"], s["path"],
            ", ".join(as_list(s["meta"].get("projects"))), s["meta"].get("status", "")))
    if len(sessions) > 25:
        L.append("- …%d older in `sessions/`" % (len(sessions) - 25))
    L += ["", "## Sessions by project", ""]
    for slug in sorted(by_project):
        L.append("- **%s**: %s" % (slug, ", ".join(
            "[%s](%s)" % (s["meta"].get("date", "?"), s["path"]) for s in by_project[slug])))
    open_items = [(d, t) for d in projects + others for t in d["open"]]
    if open_items:
        L += ["", "## Open threads (from project and topic notes)", ""]
        L += ["- [ ] %s — [%s](%s)" % (t, d["title"], d["path"]) for d, t in open_items]
    people = [d for d in others if d["path"].startswith("people/")]
    if people:
        L += ["", "## People", ""]
        L += ["- [%s](%s) — %s" % (d["meta"].get("name") or d["title"], d["path"], d["meta"].get("relation", ""))
              for d in sorted(people, key=lambda d: d["path"])]
    L += ["", "## About me and the rest", "",
          "- `me.md` profile · `now.md` cover story + upcoming · `nudges.md` reminders for me · "
          "`claude/habits.md` how Claude adapts · `ideas.md` · `inbox.md` captures to file"]
    L += ["- [%s](%s)" % (d["title"], d["path"]) for d in others if not d["path"].startswith("people/")]
    if folders:
        L += ["", "## ~/Projects folders with no notes yet", "",
              ", ".join("`%s`" % f["name"] for f in folders)]
    return "\n".join(L) + "\n"


def main():
    docs = load_notes()
    known = [p for d in docs if d["kind"] == "project" for p in as_list(d["meta"].get("paths"))]
    folders = other_folders(known)

    with open(os.path.join(NOTES, "INDEX.md"), "w", encoding="utf-8") as f:
        f.write(build_index(docs, folders))

    n = {k: sum(d["kind"] == k for d in docs) for k in ("project", "session", "note")}
    print("Built INDEX.md: %(project)d projects, %(session)d sessions, %(note)d other notes" % n)


if __name__ == "__main__":
    main()
